FORMAT: 1A
HOST: https://pinnapi.azurewebsites.net/v1

# pinnapi

Registro de inteções de eventos

## Group PIN

## PINS [/pins]

O PIN eh o recurso que memoriza a intencao do evento

### Recuperar PIN [GET /{id}]

Os atributos *Code* e *Error* indicam algum comportamento estranho.
O recurso fica no atributo *data*.
+ Parameters
    
    + id (number) - identificado do pin para recuperar
    
+ Response 200 (application/json)

        {
            "Code": 0
            "Error": {}
            "data": {
                "codigo": "01",
                "cliente": "Josue Cruz",
                "valor_aposta": 123.23,
                "palpites": [
                    {
                        "evento": "evento1",
                        "odd": "oddd1",
                    },{
                        "evento": "evento2",
                        "odd": "oddd3",
                    }
                ]
            }
        }
        
### Cria novo PIN [POST]

Voce pode criar *PIN* atraves dessa acao. Necessario passar um *JSON*
contendo os eventos das intencoes do *PIN*. Tambem pode indicar um _label_ de clientes e valores.
No caso de erro a acao retorna em seu corpo um codigo de erro e uma mensagem de erro

+ Request (application/json)

        {
            "cliente": "Josue Cruz",
            "valor_aposta": 123.23,
            "palpites": [
                {
                    "evento": "evento1",
                    "odd": "oddd1",
                },{
                    "evento": "evento2",
                    "odd": "oddd3",
                }
            ]
        }

+ Response 200 (application/json)

    + Body

            {
                "Code": 0
                "Error": {}
                "data": {
                    "codigo": "01",
                    "cliente": "Josue Cruz",
                    "valor_aposta": 123.23,
                    "palpites": [
                        {
                            "evento": "evento1",
                            "odd": "oddd1",
                        },{
                            "evento": "evento2",
                            "odd": "oddd3",
                        }
                    ]
                }
            }